### ISSUE TITLE
Frontpage

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-transparencee#1]
Simple frontpage (no blog posts, etc. just what is mentioned below)

Wireframe:
- Name: TransparenCEE
- Logo
- Oneliner: "TransparenCEE network is the greatest network in the world"
- Map of the region with logos of members (like http://codeforall.org/)
  - Logo on hover: show organisation members
- Closest "big event" (like PDF or Point) banner
- Menu

**Comment by KrzysztofMadejski** [comment]
Arek, thx for https://live.uxpin.com/5eb11a98d88612cf2b6531b30eca970afd61df00#/pages/25409119

Comments for design:
- logo could go to the top, aligned to left, instead of Home (linking always to frontpage)
- header (transparenCEE and one-liner) will stay on sub-pages but will be changed accordingly (ie. Community = Organizations and people working on pressing issues in the region)
- proposition to divide three columns by content (so it's easier to find interesting stuff)
    - news
    - community / events
    - resources (projects, research, data standards, etc)
- proposition to distinguish content types by color (palette will be available with logo)
- we need to add logos (at least ePF, Techsoup, Zasto Ne, USA) - where they will be placed
- there's a chance that we will add Cyryllic one day, should we decide now on font having full CEE charsets now, not to mess with it later? we can pay a dollar


@ArekSoldon could you (while designing) propose two versions: one wireframe-like, and second with endless-scroll (problem: what to do with the logos)?

Implementation:
- filters with no items should be hidden
- sticky top-menu
- download all content (to discuss)

**Comment by KrzysztofMadejski** [comment]
@annakuliberda  Musimy wybrać sposób kadrowania CEE

Blisko:
![cee-1](https://cloud.githubusercontent.com/assets/849975/9900787/66f666f4-5c63-11e5-8d59-112fd6687047.PNG)

Czy dalej (ale chyba też bardziej zrozumiale):
![cee-2](https://cloud.githubusercontent.com/assets/849975/9900875/0f6b8d14-5c64-11e5-98e4-9ec77573e7e0.PNG)

Granice państw, które nas nie interesują możemy pominąć tak jak w poprzednim poście.

**Comment by KrzysztofMadejski** [comment]
Finalny projekt strony głównej:
![v1](https://cloud.githubusercontent.com/assets/849975/10070745/d69c1dd0-62b4-11e5-92de-d7c4397b3076.png)

**Comment by KrzysztofMadejski** [comment]
Design:
- organizations on map
  - as dots
  - show logo on hover
- how to show person on the list (image?)
- how to show org on the list (logo?)

Implementation:
- filters with no items should be hidden
- discuss sorting of content

**Comment by alicjapeas** [comment]
![logo_europe](https://cloud.githubusercontent.com/assets/12582464/10223125/d77556ec-6857-11e5-9274-595b1f295dad.png)
![techsoupeuropelogo400x127](https://cloud.githubusercontent.com/assets/12582464/10223180/19a2176c-6858-11e5-94c6-bde18ea60ce2.png)

**Comment by KrzysztofMadejski** [comment]
@ArekSoldon dodales juz moze do designow organizacje na mapie (kropka + onhover) i facebook/twitter (patrz dwa posty temu)? Poszło to do @pkliks ?

**Comment by ArekSoldon** [comment]
![main_0201](https://cloud.githubusercontent.com/assets/3994690/10302131/b8cf36b2-6c09-11e5-8598-4ca250d9bcce.png)

**Comment by pkliks** [comment]
@KrzysztofMadejski to robimy te kropki jednak? Ostatnio rozmawialiśmy, że tylko ten licznik organizacji na hoverze (to już jest)

**Comment by KrzysztofMadejski** [comment]
Zostawmy licznik organizacji tak jak jest. Dodaj tylko FB/Twitter :)

2015-10-06 9:23 GMT+02:00 pkliks <notifications@github.com>:

> @KrzysztofMadejski <https://github.com/KrzysztofMadejski> to robimy te
> kropki jednak? Ostatnio rozmawialiśmy, że tylko ten licznik organizacji na
> hoverze (to już jest)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/epforgpl/web-transparencee/issues/1#issuecomment-145766441>
> .
>



-- 
*Krzysztof Madejski*
<karolina.wysocka@epf.org.pl>Code for Poland Program Manager / Koordynator
Koduj Dla Polski
krzysztof.madejski@epf.org.pl / +48 664 082 823

* <http://www.epf.org.pl/>*

**Comment by pkliks** [comment]
@KrzysztofMadejski kontakt, about i ikonki dodane, podaj jeszcze tylko adresy profili socialowych żebym podlinkował

**Comment by KrzysztofMadejski** [comment]
Na razie nie mamy, jak będą to podeślę. :)

2015-10-06 12:54 GMT+02:00 pkliks <notifications@github.com>:

> @KrzysztofMadejski <https://github.com/KrzysztofMadejski> kontakt, about
> i ikonki dodane, podaj jeszcze tylko adresy profili socialowych żebym
> podlinkował
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/epforgpl/web-transparencee/issues/1#issuecomment-145821279>
> .
>



-- 
*Krzysztof Madejski*
<karolina.wysocka@epf.org.pl>Code for Poland Program Manager / Koordynator
Koduj Dla Polski
krzysztof.madejski@epf.org.pl / +48 664 082 823

* <http://www.epf.org.pl/>*

**Comment by KrzysztofMadejski** [comment]
Ukryjesz na razie ikonki?

2015-10-06 18:56 GMT+02:00 Krzysztof Madejski <krzysztof.madejski@epf.org.pl
>:

> Na razie nie mamy, jak będą to podeślę. :)
>
> 2015-10-06 12:54 GMT+02:00 pkliks <notifications@github.com>:
>
>> @KrzysztofMadejski <https://github.com/KrzysztofMadejski> kontakt, about
>> i ikonki dodane, podaj jeszcze tylko adresy profili socialowych żebym
>> podlinkował
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/epforgpl/web-transparencee/issues/1#issuecomment-145821279>
>> .
>>
>
>
>
> --
> *Krzysztof Madejski*
> <karolina.wysocka@epf.org.pl>Code for Poland Program Manager / Koordynator
> Koduj Dla Polski
> krzysztof.madejski@epf.org.pl / +48 664 082 823
>
> * <http://www.epf.org.pl/>*
>



-- 
*Krzysztof Madejski*
<karolina.wysocka@epf.org.pl>Code for Poland Program Manager / Koordynator
Koduj Dla Polski
krzysztof.madejski@epf.org.pl / +48 664 082 823

* <http://www.epf.org.pl/>*

**Comment by KrzysztofMadejski** [comment]
Sorki, mamy już:

https://twitter.com/Transparen_CEE
https://www.facebook.com/transparencee/

2015-10-06 18:56 GMT+02:00 Krzysztof Madejski <krzysztof.madejski@epf.org.pl
>:

> Ukryjesz na razie ikonki?
>
> 2015-10-06 18:56 GMT+02:00 Krzysztof Madejski <
> krzysztof.madejski@epf.org.pl>:
>
>> Na razie nie mamy, jak będą to podeślę. :)
>>
>> 2015-10-06 12:54 GMT+02:00 pkliks <notifications@github.com>:
>>
>>> @KrzysztofMadejski <https://github.com/KrzysztofMadejski> kontakt,
>>> about i ikonki dodane, podaj jeszcze tylko adresy profili socialowych żebym
>>> podlinkował
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/epforgpl/web-transparencee/issues/1#issuecomment-145821279>
>>> .
>>>
>>
>>
>>
>> --
>> *Krzysztof Madejski*
>> <karolina.wysocka@epf.org.pl>Code for Poland Program Manager / Koordynator
>> Koduj Dla Polski
>> krzysztof.madejski@epf.org.pl / +48 664 082 823
>>
>> * <http://www.epf.org.pl/>*
>>
>
>
>
> --
> *Krzysztof Madejski*
> <karolina.wysocka@epf.org.pl>Code for Poland Program Manager / Koordynator
> Koduj Dla Polski
> krzysztof.madejski@epf.org.pl / +48 664 082 823
>
> * <http://www.epf.org.pl/>*
>



-- 
*Krzysztof Madejski*
<karolina.wysocka@epf.org.pl>Code for Poland Program Manager / Koordynator
Koduj Dla Polski
krzysztof.madejski@epf.org.pl / +48 664 082 823

* <http://www.epf.org.pl/>*

**Comment by KrzysztofMadejski** [comment]
- [ ] Gdy brak wartości dla danego filtra, po rozwinięciu powinno się pojawić "no matching content"
