### ISSUE TITLE
News / article

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-transparencee#10]
- Info about author (photo, organization, role)
- special case: reposts from other blog (comment + shortcut of original + read original)

**Comment by ArekSoldon** [comment]
![article](https://cloud.githubusercontent.com/assets/3994690/10175622/5a6d46ae-66f0-11e5-8594-1cb38d3501eb.png)
![special](https://cloud.githubusercontent.com/assets/3994690/10175623/5a6d700c-66f0-11e5-809b-b7d17673407c.png)

**Comment by KrzysztofMadejski** [comment]
Dzięki!

**Comment by pkliks** [comment]
@ArekSoldon podeślesz psd?

**Comment by ArekSoldon** [comment]
Jeżeli potrzebujesz :P bo to sa elementy z poprzednich ekranów :) 

https://dl.dropboxusercontent.com/u/19244622/Untitled-3.psd.zip
