### ISSUE TITLE
About / branding

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-transparencee#11]
@ArekSoldon zaprojektujesz? 
CC: @pkliks 

Content:
> We are a network of Central Eastern European and Euroasian NGOs interested in using technology in transparency and accountability work. We want to document, catalogue and scale local solutions regionally. Our objective is to ultimately make the technology for transparency work more... transparent and easier to both finance and implement.

> This website is for NGOs, practitioners, coders, activists and grant makers.
You can learn about tech tools, read news and articles and see who already forms a part of the community (people & organizations) and connect with us offline (see events) and online (check our social media or write to us!).

> The project is possible thanks to the U.S. Department of State. 

> TrasparenCEE is run by:  
[profile of an organization - miniature]
 TechSoup Europe – an enabler and connector in the world of new technologies and social change. TechSoup Europe is working on a range of programs and activities, primarily focusing on technology capacity building for civil society.
[people involved - a  miniature of persons’ profile]
      ePaństwo Foundation is an NGO operating out of Poland with a goal to support the idea of open and transparent authorities and civic engagement. They do so through giving citizens the knowledge and tools to make their country better.
      U.G. Zasto ne is a Bosnian watchdog organization and a founder of the transparency and accountability network in Southern Eastern Europe ACTION SEE.

**Comment by ArekSoldon** [comment]
![about](https://cloud.githubusercontent.com/assets/3994690/10301921/9997a7d6-6c07-11e5-8f82-1c46f74c8293.png)

**Comment by KrzysztofMadejski** [comment]
@annakuliberda @alicjapeas
http://transparencee.org/about/ tak?

**Comment by annakuliberda** [comment]
again: it's rather to @alicjapeas

On Wed, Oct 21, 2015 at 5:12 PM, Krzysiek Madejski <notifications@github.com

**Comment by alicjapeas** [comment]
Tak! Loga w monochromie. Załączam nowe TechSoupowe oraz State Department.
![techsoupeuropelogo400x127](https://cloud.githubusercontent.com/assets/12582464/10660920/c5abe9f4-78aa-11e5-84bb-327d6257a642.png)

![ct](https://cloud.githubusercontent.com/assets/12582464/10660956/03045b38-78ab-11e5-9304-986ed2412036.jpg)
![ct](https://cloud.githubusercontent.com/assets/12582464/10660955/0301c080-78ab-11e5-9ac2-6784199466ee.png)
![usflaghigh](https://cloud.githubusercontent.com/assets/12582464/10660957/03046fd8-78ab-11e5-8637-98564534a490.jpg)
![usflagweb](https://cloud.githubusercontent.com/assets/12582464/10660954/0301c3dc-78ab-11e5-8608-7793540b746b.gif)

**Comment by alicjapeas** [comment]
p.s. żadne nie jest w monochromie, bo nie ma ich w monochromie :)

**Comment by KrzysztofMadejski** [comment]
Ma być i flaga i logo? Z jakimś tekstem?

**Comment by KrzysztofMadejski** [comment]
@alicjapeas potrzebujemy wasze stare logo bez białego tła

**Comment by KrzysztofMadejski** [comment]
Loga organizacji zrobione: http://transparencee.org/about/

Pytanie co z Dep of State

**Comment by alicjapeas** [comment]
(TechSoup) Już można używać nowego logo, więc nie używajmy starego.

State Dep - tylko flaga + "The project is possible thanks to the generosity of the 
U. S. Department of State" + link (http://www.state.gov/)

**Comment by KrzysztofMadejski** [comment]
Trzeba dodać flagę większą od każdego z logo + tekst, który podała wyżej Alicja. W stopce pod logami epf /ts /zasto:

![image](https://cloud.githubusercontent.com/assets/849975/10665132/3a944b58-78c9-11e5-9dc6-25f1283286ec.png)

**Comment by pkliks** [comment]
@KrzysztofMadejski flaga i teskt dodane, logo techsoup zmienione
