### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-transparencee#12]
@alicjapeas @annakuliberda : Co powinno się znaleźć na tej stronie? Uśmiechnięta twarz Anki, mail, .. Jakiś call to action? Info o przyłączeniu się?

CC: @ArekSoldon @pkliks

**Comment by alicjapeas** [comment]
@annakuliberda jak my stoimy z kwestią mejla? na razie z tego co pamiętam Twój "prywatny", tzn. pracowy. 

Have questions or feedback? Maybe something to add? Talk to us!
akuliberda@techsoupglobal.org
krzysztof.madejski@epf.org.pl

:)

**Comment by ArekSoldon** [comment]
![contact](https://cloud.githubusercontent.com/assets/3994690/10302013/781550c6-6c08-11e5-89f4-9222180a1239.png)

**Comment by alicjapeas** [comment]
Moim zdaniem jest ok :)

**Comment by pkliks** [comment]
@ArekSoldon do tego na pewno potrzebuję psd ;)

**Comment by ArekSoldon** [comment]
https://dl.dropboxusercontent.com/u/19244622/contact.psd.zip

**Comment by KrzysztofMadejski** [comment]
@pkliks dodasz tu jeszcze nasze fotki?
http://tc.dev.inovia.pl/person/anna-kuliberda/
http://tc.dev.inovia.pl/person/krzysztof-madejski/

I można zamknąć

**Comment by pkliks** [comment]
Tak jest ok: http://tc.dev.inovia.pl/contact/ ?

**Comment by KrzysztofMadejski** [comment]
Trochę więcej światła między mailem i fotkami, proszę.

Krzysiek

On 8 October 2015 at 15:38, pkliks <notifications@github.com> wrote:

> Tak jest ok: http://tc.dev.inovia.pl/contact/ ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/epforgpl/web-transparencee/issues/12#issuecomment-146548301>
> .
>



-- 
*Krzysztof Madejski*
<karolina.wysocka@epf.org.pl>Code for Poland Program Manager / Koordynator
Koduj Dla Polski
krzysztof.madejski@epf.org.pl / +48 664 082 823

* <http://www.epf.org.pl/>*

**Comment by pkliks** [comment]
Done
