### ISSUE TITLE
Social Media links

### ISSUE THREAD

**Issue by alicjapeas** [epforgpl/web-transparencee#13]
Oto link do konta Twitterowego – potrzebujemy cover photo, najlepiej mapy  Arku, czy mógłbyś zrobić?
https://twitter.com/Transparen_CEE 
Oto link do konta Fejsbukowego – tu też potrzebujemy cover photo. Też najlepiej mapa.
https://www.facebook.com/transparencee?fref=ts

**Comment by pkliks** [comment]
Linki podpięte na stronie

**Comment by alicjapeas** [comment]
Super! @ArekSoldon : zrobiłbyś cover photos z mapy? Na Twittera i Facebooka

**Comment by ArekSoldon** [comment]
![fb_cover](https://cloud.githubusercontent.com/assets/3994690/10358751/cc40770e-6d91-11e5-93c9-de257ad0b4da.png)
![tw_cover](https://cloud.githubusercontent.com/assets/3994690/10358752/cc41f80e-6d91-11e5-9acd-2455e50c67d0.png)
