### ISSUE TITLE
Uwagi do implementacji

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-transparencee#14]
- [x] Czy fotki osób powinniśmy przycinać do kwadratowych zawsze? @ArekSoldon 
http://tc.dev.inovia.pl/person/katarzyna-batko-toluc/
- [x] Twitter account - ukrywanie przycisku na osobach gdy handle nie podany
- [x] Zdjęcia najeżdżają na logo - np. http://tc.dev.inovia.pl/person/abetare-gojani/
- [x] Wyszukane elementy powinny być zaznaczane na mapie w widoku frontpage i wszystkich content type
- [x]  W stopce nowe logo Techsoup (czarno-niebieskie załączone w #1); @alicjapeas można już nowe logo wstawić?

**Comment by pkliks** [comment]
@KrzysztofMadejski 
> Wyszukane elementy powinny być zaznaczane na mapie w widoku frontpage i wszystkich content type

tego nie rozumiem

**Comment by alicjapeas** [comment]
Nie, nie można, dopiero od 14ego października może być external facing, dam wtedy znak do zmiany.

**Comment by pkliks** [comment]
A to które jest teraz to jest nowe czy stare?

**Comment by alicjapeas** [comment]
pomarańczowe jest stare

**Comment by KrzysztofMadejski** [comment]
@pkliks apropos wyszukanych elementów i zaznaczania na mapie

Gdy wybieram pojedynczy element to zaznacz się on na mapie zgodnie z kategorią. Np. http://tc.dev.inovia.pl/organization/actionsee-network/

Podobnie na widoku strony głównej mapa powinna być podświetlona dla tych krajów, dla których jest odfiltrowany jakiś content, czyli dla tych które pojawiają się jako wartości w menu z lewej strony.

**Comment by KrzysztofMadejski** [comment]
@pkliks poprawki skonsultowane z zespołem i idziemy live:

- [ ] copy: "Community" -> "Organizations" (u góry i w filtrze po lewej)
- [ ] Person About: opis gubi się - @ArekSoldon zaproponujesz poprawki? 
  - na pewno trzeba zwiększyć czcionkę
  - może zrobić ułożenie w trzech kolumanach: fotka, organizacja (linkujące logo), opis
  - np. http://tc.dev.inovia.pl/person/vukosava-crnjanski-sabovic/
- [ ] wyświetlanie Person - dodajmy możliwość wyświetlanie na mapie, tak jak projekty i organizacje
- [ ] na głównej stronie nad filtrami drukowanymi: CLICK BELOW TO FILTER
- [ ] Na głównej stronie, czy nie lepiej jakby ilość contentu w kategorii była wyrównana do prawej? @ArekSoldon  co myślisz?
![filtes-number](https://cloud.githubusercontent.com/assets/849975/10399862/b2445666-6eb5-11e5-852b-4b95e4e0e857.PNG)
- [ ] Strzałki przy paginacji są trochę daleko od liczb, warto by je dopasować blisko liczb
![popr1](https://cloud.githubusercontent.com/assets/849975/10399890/e2ece63e-6eb5-11e5-8af2-e387d82d13f9.PNG)

**Comment by ArekSoldon** [comment]
About - pole na tekst na górze powinno być wieksze, dzięki temu nie bedzie 3 linijek... 


<img width="1106" alt="vukosava_crnjanski_sabovic___transparencee" src="https://cloud.githubusercontent.com/assets/3994690/10422632/27c56c64-70bd-11e5-911f-0eb19bf1f308.png">


co do liczb, ok moga być po prawej.

**Comment by KrzysztofMadejski** [comment]
@ArekSoldon chodzi o to, że "Founder and director of the CRTA.." jest prawie niezauważalne. Warto by zwiększyć rozmiar czcionki (w całym serwisie?).

I wygląda trochę sucho ta sekcja about. Pytanie moje (a właściwie od @annakuliberda) było, czy nie skopiować zdjęcia/nazwiska po prawej od About, a także dać logo organizacji i ułożyć to kolumnami.

**Comment by KrzysztofMadejski** [comment]
BTW: Czemu w opisie tu jest font regular http://tc.dev.inovia.pl/person/vukosava-crnjanski-sabovic/
a tu bold? http://tc.dev.inovia.pl/organization/transitions-online/
i tu bold http://tc.dev.inovia.pl/project/project-name-2-2/

**Comment by pkliks** [comment]
Wrzuć screeny bo nie bardzo widzę o co chodzi

**Comment by KrzysztofMadejski** [comment]
![bold1](https://cloud.githubusercontent.com/assets/849975/10456499/fe4ac7f2-71c1-11e5-88e4-8fd83b47d676.PNG)

![bold2](https://cloud.githubusercontent.com/assets/849975/10456502/020a0a24-71c2-11e5-882f-fcbcadc324ab.PNG)

**Comment by ArekSoldon** [comment]
Ujdenolićmy na regular, ale z możliwością bolda i już.
