### ISSUE TITLE
Uploading content

### ISSUE THREAD

**Issue by alicjapeas** [epforgpl/web-transparencee#15]
Hej @KrzysztofMadejski ja jestem out od za parę godzin do poniedziałku. Żeby nie było łyso wrzucam tekst pierwszego blog posta pt. "Hello World, it is us"

Hello World!

Hi there, here it comes: the launch of our website. It is for and about using technology in transparency and accountability related activities. We come from and focus on Central Eastern Europe and Eurasia. See who we are and what we are cooking up!

This website is for NGOs and open data practitioners, policy makers, government officials, designers and programmers. In other words: everyone interested in using technology for transparency and accountability, everyone interested in using technology for social and political purposes or in what is up in Central Eastern Europe and Eurasia. To make it short: for anyone interested. This website is for you.

The website focuses on existing projects and the community in the region as well as documents a project that TechSoup Europe, ePF Foundation and U.G. Zasto ne are working on (read more about the organizations here). It is about mapping solutions, tools and framework which are already in use, as well as promoting and scaling them. As a result of our initiative 5 different tech for transparency and accountability projects which proved successful, will be implemented in different locations within the region. We will examine the process and provide toolkits to help funders and organizations take advantage of what has already been done, so that they could benefit their communities using the resources and expertise which is already in place.

We will be posting updates as we go and providing you with the specialist content coming from the region. Get ready for our reports, the first coming will be about legal framework of Open Data in the region. We will make sure they are not only high quality content subject matter-wise, we will make it easy to read and understand. Stay tuned!

The TransparenCEE project is possible thanks to the funding from the U.S. Department of State.

**Comment by KrzysztofMadejski** [comment]
Thx!

On 7 October 2015 at 13:00, Alicja Peszkowska <notifications@github.com>
wrote:

> Hej @KrzysztofMadejski <https://github.com/KrzysztofMadejski> ja jestem
> out od za parę godzin do poniedziałku. Żeby nie było łyso wrzucam tekst
> pierwszego blog posta pt. "Hello World, it is us"
>
> Hello World!
>
> Hi there, here it comes: the launch of our website. It is for and about
> using technology in transparency and accountability related activities. We
> come from and focus on Central Eastern Europe and Eurasia. See who we are
> and what we are cooking up!
>
> This website is for NGOs and open data practitioners, policy makers,
> government officials, designers and programmers. In other words: everyone
> interested in using technology for transparency and accountability,
> everyone interested in using technology for social and political purposes
> or in what is up in Central Eastern Europe and Eurasia. To make it short:
> for anyone interested. This website is for you.
>
> The website focuses on existing projects and the community in the region
> as well as documents a project that TechSoup Europe, ePF Foundation and
> U.G. Zasto ne are working on (read more about the organizations here). It
> is about mapping solutions, tools and framework which are already in use,
> as well as promoting and scaling them. As a result of our initiative 5
> different tech for transparency and accountability projects which proved
> successful, will be implemented in different locations within the region.
> We will examine the process and provide toolkits to help funders and
> organizations take advantage of what has already been done, so that they
> could benefit their communities using the resources and expertise which is
> already in place.
>
> We will be posting updates as we go and providing you with the specialist
> content coming from the region. Get ready for our reports, the first coming
> will be about legal framework of Open Data in the region. We will make sure
> they are not only high quality content subject matter-wise, we will make it
> easy to read and understand. Stay tuned!
>
> The TransparenCEE project is possible thanks to the funding from the U.S.
> Department of State.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/epforgpl/web-transparencee/issues/15>.
>



-- 
*Krzysztof Madejski*
<karolina.wysocka@epf.org.pl>Code for Poland Program Manager / Koordynator
Koduj Dla Polski
krzysztof.madejski@epf.org.pl / +48 664 082 823

* <http://www.epf.org.pl/>*
