### ISSUE TITLE
Rozmiary fotek

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-transparencee#16]
Powinniśmy chyba normalizować rozmiary fotek ludzi (najlepiej w edytorze WP), bo inaczej wychodzi trochę sieczka: http://tc.dev.inovia.pl/event/personal-democracy-forum-poland-cee-2015/

@ArekSoldon, @pkliks co myślicie?

**Comment by ArekSoldon** [comment]
no powinno być tak ze cropuje do jednego rozmiaru

**Comment by pkliks** [comment]
Cropowanie do jednego rozmiaru z automatu jest złym pomysłem, bo to może poobcinać ludzi. Z tego co widziałem na niektórych osoby nie są centralnie na zdjęciu.

**Comment by KrzysztofMadejski** [comment]
Możemy ręcznie edytować, do jakiego rozmiaru? Czy Wordpress ma możliwość
rozszerzenia zdjęcia, jeżeli np. jest za niskie?

2015-10-08 10:32 GMT+02:00 pkliks <notifications@github.com>:

> Cropowanie do jednego rozmiaru z automatu jest złym pomysłem, bo to może
> poobcinać ludzi. Z tego co widziałem na niektórych osoby nie są centralnie
> na zdjęciu.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/epforgpl/web-transparencee/issues/16#issuecomment-146457533>
> .
>



-- 
*Krzysztof Madejski*
<karolina.wysocka@epf.org.pl>Code for Poland Program Manager / Koordynator
Koduj Dla Polski
krzysztof.madejski@epf.org.pl / +48 664 082 823

* <http://www.epf.org.pl/>*

**Comment by pkliks** [comment]
Rozszerzyć się nie da. Co do rozmiaru to ważniejsze tutaj jest ratio żeby powstał kwadrat, minimum 200x200

**Comment by KrzysztofMadejski** [comment]
No racja. Thx!
