### ISSUE TITLE
Numbers on the map - add content to numbers?

### ISSUE THREAD

**Issue by alicjapeas** [epforgpl/web-transparencee#25]
I think we need to explain what are these numbers when you hover on the map mean - because it isn't true that there are 0 organizations in Ukraine. we need to somehow explain what we mean. Should we add more text, what do you think @annakuliberda and @KrzysztofMadejski

**Comment by KrzysztofMadejski** [comment]
I'd change this popups to show only name of country. I don't think number of organizations is needed. What'ya think?

**Comment by annakuliberda** [comment]
I'd change this only if there is zero orgs in the given search.

On Wed, Oct 21, 2015 at 5:07 PM, Krzysiek Madejski <notifications@github.com

**Comment by alicjapeas** [comment]
I like the country names also because it isn't easy for some people to know what is what, since the countries aren't signed.

**Comment by KrzysztofMadejski** [comment]
@pkliks Podsumowując: Zamieniamy w dymkach ilość organizacji na Nazwę Kraju

**Comment by pkliks** [comment]
@KrzysztofMadejski a podświetlenie zostaje jak jest?

**Comment by KrzysztofMadejski** [comment]
potrzebujemy na mapie 3 kolor: do podświetlania. Bo teraz onhover nie wyróżnia tych krajów, dla których jet content, bo to ten sam kolor.

**Comment by ArekSoldon** [comment]
#5c74b8 dla bez contentu.
