### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by alicjapeas** [epforgpl/web-transparencee#26]
Filters don't always work – is it clear what they serve for for the user then? They work e.g. when you pull out organization's content and what to filter by country. But if you don't choose any content first they dont. Or when you apply people to projects they don't work either. Should they? Should we better explain when filtering works? With words (pop up) or differently? @annakuliberda & @KrzysztofMadejski

**Comment by KrzysztofMadejski** [comment]
Please post links and explain what the expected behaviour should be

**Comment by alicjapeas** [comment]
I do not know :) I am just wondering. I will think about it and let you know in the afternoon.

**Comment by KrzysztofMadejski** [comment]
Without expected behaviour you cannot tell if sth work or not :-)

**Comment by alicjapeas** [comment]
Ok, I think the case was that there was not enough content for filters to apply always. I think it is clear now. Thanks!

**Comment by KrzysztofMadejski** [comment]
Yes, we worked a bit on filters only to show categories that are available.
