### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by alicjapeas** [epforgpl/web-transparencee#27]
1. [x] "transparency work more… transparent" (remove the dots)
2. [x] hyperlink the text: see events + check our social media... + the US department of State
3. [x] There is no US State Deprtament flague anywhere. It should be in the mock ups, I upload it below
4. [x] Why don't we have Wojtek on the site Should we add him @annakuliberda ?
7. [ ] in the FLOSSK description two different sizes of fonts are used

**Comment by KrzysztofMadejski** [comment]
I take:
5. [ ] Organizations descriptions: some don't have logos. If they don't we need to remove the "LOGO" txt from there, cause it looks unprofessional
6. [ ] We should add POINT conferences to events

**Comment by annakuliberda** [comment]
1. Why don't we have Wojtek on the site Should we add him @annakuliberda
   <https://github.com/annakuliberda> ?

No Wojtek, because he wasn't in the speakers pool, I'd leave it like it is.

On Wed, Oct 21, 2015 at 5:04 PM, Krzysiek Madejski <notifications@github.com

**Comment by alicjapeas** [comment]
Hey @annakuliberda , I think we could add Community boost_r camp, have Wojtek as a speaker from the last year's POINT and also include Agata J. (#cbcamp)?

**Comment by alicjapeas** [comment]
or just not :)

**Comment by annakuliberda** [comment]
yes we can, and for Zasto ne Tijana is missing (there is no waman there,
that is why I'm telling this ;)

On Thu, Oct 22, 2015 at 1:11 PM, Alicja Peszkowska <notifications@github.com

**Comment by KrzysztofMadejski** [comment]
You can add whatever you feel should be added.
