### ISSUE TITLE
Analysis 

### ISSUE THREAD

**Issue by alicjapeas** [epforgpl/web-transparencee#28]
Should we remove this from the menu for the time being and add it once we upload reports?
Should we be able to upload reports so that people can read them in a nice way? I mean isssuu style of reading not just downloading a PDF - is it possible? What will be the form of reports? Will we be formating them on the site every time?
@annakuliberda @KrzysztofMadejski

**Comment by KrzysztofMadejski** [comment]
Remove menu - we won't bother. We can post almost blank analysis saying what will be included here in the future. Or we can post legal research.

Styling - Depending on the report. We will do that on case by case basis.

**Comment by alicjapeas** [comment]
Ok. Let's write: "The first analysis about the legal framework of openess in CEE and Eurasia is coming up in the beginning of November. Stay tuned."
