### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-transparencee#3]
IT Tools that are the effect of network collaboration (at first projects that we are scaling)

Tool:
- Name
- Oneliner
- Description
- Map of region showing implementation status [working, in progress, good ground, no research done], long description of status shown in popup
- Meta
  - Why scale: text 
  - How to replicate: text
  - Support cost: text 
  - Technology: (list of tags like Python, Django)
  - Content: scraped / manual

? List of tools - how to present?

**Comment by KrzysztofMadejski** [comment]
![tool](https://cloud.githubusercontent.com/assets/849975/10098942/989dd204-6385-11e5-8756-03134c6bf64c.png)

**Comment by KrzysztofMadejski** [comment]
Design:
- "Tool website" powinno moim zdaniem być powtórzone pod useful info "Go to project website"

Implementacja:
- Sekcje "Why Scale", "how to replicate": tytuły powinny być wpisywane z palca
- Copy: Zmieńmy wszędzie Tool na Project

**Comment by ArekSoldon** [comment]
![tool_project](https://cloud.githubusercontent.com/assets/3994690/10124370/f71e92c6-6553-11e5-95fa-9eff714459d5.png)

tool i project będzie wyglądał tak samo...

**Comment by KrzysztofMadejski** [comment]
Implementacja:
- Z Tool już zrezygnowaliśmy, będą tylko Projects.
- Copy: Deployed by, a nie developed by.

Dzięki!
