### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-transparencee#31]
Przygotujesz na podstawie logo?

Do uploadu tu http://transparencee.org/wp-content/themes/transparencee/images/favicon.png (to już ja zrobię)

**Comment by ArekSoldon** [comment]
![fav](https://cloud.githubusercontent.com/assets/3994690/10675124/ba0d7046-78fe-11e5-99bd-2b926ba7b1f8.png)
