### ISSUE TITLE
About: TransparenCEE is run by

### ISSUE THREAD

**Issue by alicjapeas** [epforgpl/web-transparencee#34]
![anka](https://cloud.githubusercontent.com/assets/12582464/10687843/70270e0c-7970-11e5-8768-3e1e9ecdfdd4.jpg)
Can we please change the TechSoup Europe logo here + our pictures to the ones pasted below

![image](https://cloud.githubusercontent.com/assets/12582464/10687816/3ef47766-7970-11e5-8620-eb847abfe118.png)

![21501595400_d7a1f01bbb_o](https://cloud.githubusercontent.com/assets/12582464/10687835/5f9862ca-7970-11e5-9004-a5fe539fcb88.jpg)
![ania 2](https://cloud.githubusercontent.com/assets/12582464/10687839/675ce9b8-7970-11e5-8b15-c390caa77f05.jpg)

**Comment by KrzysztofMadejski** [comment]
Yes you can

On 23 October 2015 at 10:25, Alicja Peszkowska <notifications@github.com>
wrote:

> [image: anka]
> <https://cloud.githubusercontent.com/assets/12582464/10687843/70270e0c-7970-11e5-8768-3e1e9ecdfdd4.jpg>
> Can we please change the TechSoup Europe logo here + our pictures to the
> ones pasted below
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/12582464/10687816/3ef47766-7970-11e5-8620-eb847abfe118.png>
>
> [image: 21501595400_d7a1f01bbb_o]
> <https://cloud.githubusercontent.com/assets/12582464/10687835/5f9862ca-7970-11e5-9004-a5fe539fcb88.jpg>
> [image: ania 2]
> <https://cloud.githubusercontent.com/assets/12582464/10687839/675ce9b8-7970-11e5-8b15-c390caa77f05.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/epforgpl/web-transparencee/issues/34>.
>



-- 
*Krzysztof Madejski*
<karolina.wysocka@epf.org.pl>Code for Poland Program Manager / Koordynator
Koduj Dla Polski
krzysztof.madejski@epf.org.pl / +48 664 082 823

* <http://www.epf.org.pl/>*

**Comment by alicjapeas** [comment]
Can you please do it? Let's have a little content-add-up training next week to make sure you do not have to do it in the future and we will better plan, but for now I think it is the fastest we can do, and we need to promote today..
