### ISSUE TITLE
Zasto ne logo

### ISSUE THREAD

**Issue by alicjapeas** [epforgpl/web-transparencee#35]
Can we change Zasto ne logo in the footer and in About to the coloured one?

![zastone_logo-300x100](https://cloud.githubusercontent.com/assets/12582464/10687930/eba1c888-7970-11e5-8e9a-96f64788e8de.png)

**Comment by KrzysztofMadejski** [comment]
Zmienione:
- http://transparencee.org/organization/why-not/
- http://transparencee.org/about/
- w stopce
