### ISSUE TITLE
Events missing

### ISSUE THREAD

**Issue by alicjapeas** [epforgpl/web-transparencee#36]
Hey, can we all the events as events-content-types?

https://docs.google.com/spreadsheets/d/1rAew9mc9b6tvh079Qn9Uf3Qktdn10HJjn19gCRELK2E/edit#gid=0

**Comment by alicjapeas** [comment]
What I meant was: can you add all the events from the spreadsheet? :)

**Comment by KrzysztofMadejski** [comment]
I added all of them. Also added speakers (apart from point 1,2,3). I'm wondering if listing speakers is providing any info. We need to think about it later.
