### ISSUE TITLE
Wyróżnione pozycje

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-transparencee#37]
Umknęło mi po którejś z naszych pierwszych rozmów umieszczenie tego jako issue.

Każdy typ contentu miał posiadać checkbox "wyróżnione". Pozycje, w których byłby zaznaczony ten box powinny się wyświetlać na głównej stronie (gdy jest domyślne sortowanie).

**Comment by pkliks** [comment]
doszedł wybór w edycji (na dole) Is sticky
