### ISSUE TITLE
Adding Apps4Warsaw to the Projects

### ISSUE THREAD

**Issue by alicjapeas** [epforgpl/web-transparencee#38]
@KrzysztofMadejski: Czy mógłbyś proszę dodać Dane po warszawsku do raportu o technologiach?
I koniecznie na stronę. 

[image](https://cloud.githubusercontent.com/assets/12582464/10821063/a658109a-7e50-11e5-991f-88504e35f323.png)

**Comment by alicjapeas** [comment]
Link to the Apps4Warsaw github: https://github.com/MUNDO-platform/srccode.git      
Link to the website: www.apps4warsaw.org

Apps4Warsaw (in PL: "Dane po warszawsku") is more than a competition for the best city apps built upon City of Warsaw publically available open data. Apps4Warsaw promotes open data and engages people in creating civic technology tools for their city. 

Throughout the project we selected the data sets to be open, designed and built a unique technical environment where data is stored and published, planned and conducted the open data contest, developed all the necessary procedures within the City for the opening process to be continued.

**Comment by KrzysztofMadejski** [comment]
http://transparencee.org/project/apps4warsaw/
