### ISSUE TITLE
Linki nie są wyróżnione

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-transparencee#39]
Np. "Faktograf.hr" na http://transparencee.org/news/faktograf-launches-in-croatia/
Lub https://mojepanstwo.pl/dane/zbiory na http://transparencee.org/project/mycountry/

@ArekSoldon  jak to powinno wyglądać?

**Comment by ArekSoldon** [comment]
<img width="620" alt="screen shot 2015-12-09 at 07 12 12" src="https://cloud.githubusercontent.com/assets/3994690/11677996/3371956a-9e44-11e5-8bef-6681e31c961f.png">

normlany #175fa6
najechany #ff705b
odwiedozny #2885e0
