### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-transparencee#4]
- Header
 - Logo
 - Name (en + local)
 - Country
 - Link to site
- Position on map
- Members (relation) (photo, name surname, role)
- Projects (relation) (image, name, short desc)
- Presentations at events (relation) (like in person https://github.com/epforgpl/web-transparencee/issues/5)

**Comment by KrzysztofMadejski** [comment]
W sekcjach wylistować powiązane obiekty wg. #7:
- members
- events
- projects

**Comment by ArekSoldon** [comment]
![organization](https://cloud.githubusercontent.com/assets/3994690/10128490/c5d22b28-65b3-11e5-9165-96f6b2a206e1.png)

**Comment by KrzysztofMadejski** [comment]
Copy: Other organizatons -> "Others"

**Comment by pkliks** [comment]
@KrzysztofMadejski Czy na tym i innych tego typu widokach przy listach np.: Eventów jest sens umieszczać nad tytułem rodzaj skoro jest podpisany po lewej i przy każdym będzie ten sam?

**Comment by KrzysztofMadejski** [comment]
Ad 1. Słuszna uwaga. Rodzaju nad tytułem nie pokazujmy.
Ad 2. Ukryj całą sekcję.
