### ISSUE TITLE
Wyszukiwanie w serwisie

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-transparencee#41]
Design:
- [ ] box wyszukiwania
- [ ] lista wyników

**Comment by ArekSoldon** [comment]
![search](https://cloud.githubusercontent.com/assets/3994690/11678142/468280fa-9e45-11e5-9d57-f4af60e9bed8.png)

![main_0201](https://cloud.githubusercontent.com/assets/3994690/11678194/90e23db6-9e45-11e5-8289-a7da5383c3ac.png)

**Comment by pkliks** [comment]
@ArekSoldon podrzuć proszę ikonę szukajki

**Comment by ArekSoldon** [comment]
@pkliks svg? png?

**Comment by pkliks** [comment]
@ArekSoldon svg jak masz :)

**Comment by ArekSoldon** [comment]
dla ciebie zawsze :) 
[Untitled-1.svg.zip](https://github.com/epforgpl/web-transparencee/files/61191/Untitled-1.svg.zip)

**Comment by pkliks** [comment]
Dzięki :D
