### ISSUE TITLE
Skalowanie obrazka

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-transparencee#46]
http://transparencee.org/news/faktograf-launches-in-croatia/

**Comment by alicjapeas** [comment]
http://transparencee.org/news/scaling-projects-why-how/

Próbowałam z opcją customize size, ale medium jest za małe, large za duże, a do "custom" się nie skaluje...

**Comment by KrzysztofMadejski** [comment]
Ustawiłem custom na 600 i już działa. Wyświetla się 600 i się skaluje w dół wraz ze stroną. Sprawdzisz u siebie i zamkniesz jeżeli jest ok?

**Comment by alicjapeas** [comment]
ok!

**Comment by alicjapeas** [comment]
przysięgam, że mój mózg nie działa już. Albo tylko Ty możesz zamknąc, bo jesteś ownerem albo ja po prostu nie wiem jak to zrobić...

**Comment by KrzysztofMadejski** [comment]
Hm, możliwe że faktycznie jestem ownerem.
