### ISSUE TITLE
Kolejna zmiana loga TechSoup

### ISSUE THREAD

**Issue by alicjapeas** [epforgpl/web-transparencee#47]
Cześć, w związku z rebrandingiem przechodzimy różne zawirowania. Zdecydowaliśmy się używać na wszystkich stronach po prostu loga TechSoup mimo że pisac będziemy o TechSoup Europe.

Proszę o podmiankę w stopce i w about us. Logo zał
![techsoup_logo_png](https://cloud.githubusercontent.com/assets/12582464/11741507/d2d275aa-9ff9-11e5-898a-a5b7b8da5f52.png)
ączam, dziękuję ślicznie.

**Comment by KrzysztofMadejski** [comment]
Zmieniłem About us, @pkliks zmienisz w stopce?

@alicjapeas Tobie zostawiam http://transparencee.org/organization/techsoup-europe/ jeżeli tu też chcecie zmienić.

**Comment by alicjapeas** [comment]
@pkliks zmień proszę w stopce, ja zmieniłam na stronie o TS. dzięki!
