### ISSUE TITLE
Nie pokazuje mi się teorytycznie opublikowany post

### ISSUE THREAD

**Issue by alicjapeas** [epforgpl/web-transparencee#48]
Oto on: http://transparencee.org/scaling-projects-why-how/

What is wrong? #help!

**Comment by pkliks** [comment]
Hej, zasadniczo nie ma w serwisie czegoś do czego używane są posts. Albo do news albo do analysis wpisy są dodawane

**Comment by alicjapeas** [comment]
ok. Wspaniale, czyli zrobiłam głupi błąd. Dziękuję
