### ISSUE TITLE
Różne czcionki, nagłówki i rozmiary

### ISSUE THREAD

**Issue by alicjapeas** [epforgpl/web-transparencee#49]
Czy możemy coś takiego wprowadzić?

**Comment by KrzysztofMadejski** [comment]
Co dokładnie potrzebujesz? Ile poziomów nagłówków? Po co inne czcionki? Pogrubienie, kursywa nie wystarczy?

Zawsze możesz edytować bezpośrednio html, ale to może rozjechać wygląd.

**Comment by alicjapeas** [comment]
To inne czcionki nie, ale co najmniej dwa poziomy:
Tytuł i taki nagłowek do śródtytułów. Ok? Będzie ciekawiej graficznie wyglądać, a teraz nie ma jak zmienić rozmiarów.

**Comment by KrzysztofMadejski** [comment]
Możesz stosować <h2><h3> przełączając się na edytor HTML, lub używać
pogrubienia i drukowanymi pisać jako sekcje. Spróbuj, zobacz czy wystarczy?

Krzysiek

2015-12-23 18:32 GMT+01:00 Alicja Peszkowska <notifications@github.com>:

> To inne czcionki nie, ale co najmniej dwa poziomy:
> Tytuł i taki nagłowek do śródtytułów. Ok? Będzie ciekawiej graficznie
> wyglądać, a teraz nie ma jak zmienić rozmiarów.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/epforgpl/web-transparencee/issues/49#issuecomment-166951015>
> .
>



-- 
*Krzysztof Madejski*
<karolina.wysocka@epf.org.pl>Code for Poland Program Manager / Koordynator
Koduj Dla Polski
krzysztof.madejski@epf.org.pl / +48 664 082 823

* <http://www.epf.org.pl/>*

**Comment by KrzysztofMadejski** [comment]
@alicjapeas czy moja ostatnie sugestia pomogła?

**Comment by alicjapeas** [comment]
tak, tak robie teraz :) dzieki!
