### ISSUE TITLE
Person

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-transparencee#5]
- Image
- Name
- Organization (clickable, relation) + role in it
- Short twitter-like bio
- List of public appearances (image, name of event, where, subject - linking events [relation m2m])

**Comment by ArekSoldon** [comment]
![Uploading person.png…]()
![peoplelist](https://cloud.githubusercontent.com/assets/3994690/10128555/b1f2b7de-65b4-11e5-9862-ce930303694c.png)

**Comment by ArekSoldon** [comment]
![person](https://cloud.githubusercontent.com/assets/3994690/10128558/b97ebd90-65b4-11e5-8929-b7546ac438f6.png)
![peoplelist](https://cloud.githubusercontent.com/assets/3994690/10128557/b97e256a-65b4-11e5-82da-7eb0000ceb7d.png)

**Comment by KrzysztofMadejski** [comment]
Drugi design: our community - to będzie lista organizacji, a nie osób. Filtry powinny być widoczne, podobnie jak na frontpage. Także sortowanie A-Z.

**Comment by KrzysztofMadejski** [comment]
@ArekSoldon co myślisz o logu organizacji pod fotką zamiast tekstu?

**Comment by ArekSoldon** [comment]
ale gdzies musimy listować ludzi... 
co do logo pod mordkami, to wiesz jak jest, logasy są różne i obawiam się że 1. bedzie pstrokacizna, 2. mogą być niektóre źle widoczne.

**Comment by KrzysztofMadejski** [comment]
Ad ludzie: Będą wylistowani na podstronach jako members organizacji i speakerzy eventów
Ad loga: ok, zostańmy przy tekście

**Comment by alicjapeas** [comment]
Tylko tekstu pod zdjęciem będzie więcej niż 3 literki :)
