### ISSUE TITLE
Niepoprawna mapa

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-transparencee#51]
@pkliks nie wiem skąd wziąłeś tą mapę, ale trzeba dorysować:
- [ ] Gruzję
- [ ] Kosowo

Brak popupów na:
- [ ] Turcji
- [ ] Bośni i Herzegowinie

https://www.openstreetmap.org/#map=6/44.481/26.960&layers=T

![image001](https://cloud.githubusercontent.com/assets/849975/12033723/b96cece0-ae26-11e5-824a-d6cdb2fd8e59.jpg)

**Comment by pkliks** [comment]
@KrzysztofMadejski mapę mam od @ArekSoldon i On musi wprowadzić zmiany na niej wtedy podmienię

**Comment by ArekSoldon** [comment]
poprawiona mapa.

[mapa.svg.zip](https://github.com/epforgpl/web-transparencee/files/74733/mapa.svg.zip)
