### ISSUE TITLE
Dodać tytuł w treści artykułu na Analysis

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-transparencee#53]
![tcee-tytul-analysis](https://cloud.githubusercontent.com/assets/849975/12615334/6dc6bbb8-c505-11e5-944b-83f7d0843b5e.PNG)

W News też tak?

**Comment by annakuliberda** [comment]
tak, to rozwiąże sprawę, w newsach też super! :)

On Wed, Jan 27, 2016 at 2:52 PM, Krzysiek Madejski <notifications@github.com

**Comment by KrzysztofMadejski** [comment]
To już zostało wdrożone.
