### ISSUE TITLE
Linki w podpunktach się nie wyświetlają

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-transparencee#54]
http://transparencee.org/analysis/open-data-principles-for-beginners/

![12650160_10154524633639942_765944030_n](https://cloud.githubusercontent.com/assets/849975/12615406/c8607eba-c505-11e5-8376-95cb588ddfab.jpg)

Trzeba by chyba usunąć `p` lub dać inny pośredni container, albo explicite listy w `.content-wrapper p a:hover`

**Comment by annakuliberda** [comment]
hej, coś się z tym dzieje?

On Wed, Jan 27, 2016 at 2:54 PM, Krzysiek Madejski <notifications@github.com
