### ISSUE TITLE
Brak zdjęć przy udostępnianiu linków, np. na FB

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-transparencee#55]
Przez co, np. na FB się linkuje bez zdjęcia:

 - http://transparencee.org/news/disreconnecting-citizens-personal-democracy-forum-pl-cee-2016-sign-up-today/
- FB: https://developers.facebook.com/tools/debug/og/object/?q=http%3A%2F%2Ftransparencee.org%2Fnews%2Fdisreconnecting-citizens-personal-democracy-forum-pl-cee-2016-sign-up-today%2F

Działanie (rozumiem, że to się przekłada na meta tag `og:image`):
- powinna być możliwość ustalić featured image, lecz  domyślnie powinien zaciągać, tak jak jest poniżej wyszczególnione
- dla news i articles pierwszy obrazek wklejony w treść artykułu (tak jest domyślnie przecież w Post-ach)
- w projects powinien brać "project logo" - np. http://transparencee.org/wp-admin/post.php?post=545&action=edit
- w organizations powinien brać "logo"
- w people powinien brać "logo"
- w events powinien brać "logo"

**Comment by pkliks** [comment]
Dodałem og:image oraz możliwość cusotomowego ustawienia go (w edycji wpisów Facebook - image),

> dla news i articles pierwszy obrazek wklejony w treść artykułu (tak jest domyślnie przecież w Post-ach)
Nie do końca tak jest. Standardowo w motywach WP pierwsza fotka w tekście na samej górze to Featured Image - w transparencee tego nie ma, fotki pojawiają się dopiero w tekście i tu już kwestia jak Facebook sobie to sczyta, a ma swoje wymogi odnośnie wielkości i ratio fotek stąd też różnie to wypada. Najlepiej jakbyście ustawiali customowe te obrazki według wytycznych FB, wtedy macie pewność że one się własnie pojawią.
