### ISSUE TITLE
Zmiany w  zespole TechSoup w "About"?

### ISSUE THREAD

**Issue by alicjapeas** [epforgpl/web-transparencee#56]
1. Dodać Chrisa Wormana do zespołu TechSoup
tu jest on: http://transparencee.org/person/chris-worman/

2. Zmienić Anny Sienickiej tytuł na "Vice President, Europe"

tu jest strona about: http://transparencee.org/about/

@KrzysztofMadejski, Nie wiem jak edytować ludzi, przepraszam!

cc @annakuliberda :)

**Comment by KrzysztofMadejski** [comment]
Wchodzisz w edycję organizacji -> http://transparencee.org/wp-admin/post.php?post=296&action=edit
tam wpisujesz pozycje i wybierasz ludzi.

Zmieniłem pozycję i dodałem Chrisa, ale bez pozycji. Możesz teraz sama dodać jak już wiesz jak.
