### ISSUE TITLE
Content on the website

### ISSUE THREAD

**Issue by alicjapeas** [epforgpl/web-transparencee#57]
1. NEWS & ANALYSIS: When you browse through the news on your phone the first thing you get is a big picture of an author, i think the picture added to the text or the text should come first

2. ORDER OF THE NEWS: I have unstuck all the news - can they automatically put themselves in an order from the oldest to the newest (on top), it is "al reves" right now, so the oldest one are on top

cc @KrzysztofMadejski when he is back from holidays :)

**Comment by annakuliberda** [comment]
odnośnie pt. 2. czy można to naprawić?
czy pt 1. został załatwiony?
