### ISSUE TITLE
branding

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-transparencee#6]
>  must be marked appropriately with the standard U.S. flag in a size and prominence equal to (or greater than) any other logo or identity.

**Comment by alicjapeas** [comment]
Did we alrady receive the flague in the right format? @annakuliberda?

**Comment by annakuliberda** [comment]
not yet, but working on it

**Comment by alicjapeas** [comment]
Hej @annakuliberda , nie możemy wystawić strony bez tego loga na widok publiczny. Just sayin...

**Comment by annakuliberda** [comment]
NA razie trzbea pisać, ze generous sponsorship.
na dole może gdzieś i na pewno w About


On Wed, Oct 7, 2015 at 12:00 PM, Alicja Peszkowska <notifications@github.com

**Comment by alicjapeas** [comment]
@annakuliberda proszę jak Mark odpisze, wklej tu zdanie z mojego mejla do wykorzystania zamiast loga, jeśli nie dostaniemy loga, ok?

**Comment by annakuliberda** [comment]
this is more to @alicjapeas

On Wed, Oct 21, 2015 at 5:13 PM, Krzysiek Madejski <notifications@github.com
