### ISSUE TITLE
Możliwość wyświetlania banera poziomego na stronie głównej pod mapą

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-transparencee#61]
- [x] Ustawianie obrazka oraz linku z poziomu panela admina

**Comment by pkliks** [comment]
W edycji strony głównej doszły stosowne pola. Warunek wyświetlania bannera jest ustawiony na to czy obrazek jest uzupełniony czy nie

**Comment by KrzysztofMadejski** [comment]
Dzięki!
