### ISSUE TITLE
Event page

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/web-transparencee#8]
![event](https://cloud.githubusercontent.com/assets/849975/10098948/a54cf6ce-6385-11e5-9bec-9b6b4c72578d.png)

**Comment by KrzysztofMadejski** [comment]
Design:
- "Go to event website" jako bardziej widoczny call-to-action także pod opisem eventu
- wylistować organizatorów w osobnej sekcji
- wylistować speakerów (tytuł sesji, zdjęcie, imię nazwisko)

Implementacja:
- atrybuty relacji (dla event-person to będzie tytuł sesji)

**Comment by ArekSoldon** [comment]
![event](https://cloud.githubusercontent.com/assets/3994690/10124467/161f8e3a-6556-11e5-9278-e669c46ffa48.png)

**Comment by ArekSoldon** [comment]
![event](https://cloud.githubusercontent.com/assets/3994690/10128496/cf513df6-65b3-11e5-86f2-b27134f869b9.png)

**Comment by KrzysztofMadejski** [comment]
@alicjapeas, czy OTHER EVENTS mają być losowane, czy może wybierane ręcznie.

Podobnie OTHER PROJECTS, OTHER ARTICLES, OTHER NEWS - trzeba zadecydować, jak to ma być obsługiwane.

**Comment by alicjapeas** [comment]
kalendarzowo? tzn. ostatnie?

**Comment by KrzysztofMadejski** [comment]
EVENT - najnowsze eventy
PROJECTS - losowo (tu kalendarzowo nie ma sensu)
ARTICLES - losowo, z podobnymi hashtagami?
NEWS - z tego samego kraju? Z podobnymi hashagami? (ostatnie będą na stronie głównej)
ORGANIZATION - losowo

+ opcja wyboru ręcznie gdy się chce wyświetlić konkretne?

**Comment by KrzysztofMadejski** [comment]
@pkliks : jeden bug
- [ ] fotki osób powinny linkować do ich profili: nie działa na http://tc.dev.inovia.pl/event/personal-democracy-forum-poland-cee-2015/
